/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DataInterfaceForward_CONSTANTS_H
#define DataInterfaceForward_CONSTANTS_H

#include "DataInterfaceForward_types.h"



class DataInterfaceForwardConstants {
 public:
  DataInterfaceForwardConstants();

};

extern const DataInterfaceForwardConstants g_DataInterfaceForward_constants;



#endif
