/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "DataInterfaceForward_constants.h"



const DataInterfaceForwardConstants g_DataInterfaceForward_constants;

DataInterfaceForwardConstants::DataInterfaceForwardConstants() {
}



