/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "PushMessage_constants.h"



const PushMessageConstants g_PushMessage_constants;

PushMessageConstants::PushMessageConstants() {
}



