// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "PushMessage.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class PushMessageHandler : virtual public PushMessageIf {
 public:
  PushMessageHandler() {
    // Your initialization goes here
  }

  void push(std::vector<std::string> & _return, const std::vector<std::string> & messages) {
    // Your implementation goes here
    printf("push\n");
  }

  void registerCompleteNotify(std::map<std::string, std::string> & _return, const std::map<std::string, std::string> & mappara) {
    // Your implementation goes here
    printf("registerCompleteNotify\n");
  }

};
/*
int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<PushMessageHandler> handler(new PushMessageHandler());
  shared_ptr<TProcessor> processor(new PushMessageProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}
*/
