/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PushMessage_CONSTANTS_H
#define PushMessage_CONSTANTS_H

#include "PushMessage_types.h"



class PushMessageConstants {
 public:
  PushMessageConstants();

};

extern const PushMessageConstants g_PushMessage_constants;



#endif
